config/routes.rb
Flash::Application.routes.draw do
  devise_for :users

  resources :cards, except: [:show] do
    collection do
      match 'search' => 'cards#index', via: [:get, :post], as: :search
    end
  end
  resources :card_imports, only: [:new,:create]
  resources :tags, except: [:show]
  resources :users, only: [:show]
  resources :review_lists, only: [:show, :new, :create]
  resources :pages do
    collection do
      match 'search' => 'pages#search', via: [:get, :post], as: :search
    end
  end

  get "/cards/:card_id", to: "cards#index", as: "cards_card"

  get "/tags/:tag_id", to: "tags#index", as: "tags_tag"

  post "/remove/:tag_id", to: "tags#remove", as: "tags_removetag"

  get "/review", to: "pages#review", as: "review"

  get "/share/(:page)", to: "pages#share", as: "share"

  get "/users/:id/:tag_id/(:page)", to: "pages#sharetag", as: "share_tag"

  post "/copy/:tag_id", to: "pages#copy", as: "copy"

  root 'pages#home'
end

app/models/card.rb
class Card < ActiveRecord::Base
  include SuperMemo::SM2

  has_many :taggings,
    inverse_of: :card,
    dependent: :destroy
  has_many :tags,
    through: :taggings,
    inverse_of: :cards
  has_many :review_list_cards,
    dependent: :destroy
  has_many :review_lists,
    through: :review_list_cards,
    inverse_of: :cards
  belongs_to :user,
    inverse_of: :cards

  validates_presence_of :front
  validates_presence_of :back
  validates_presence_of :user

  paginates_per 20

  def self.to_csv
    CSV.generate do |csv|
      csv << ['front','back','tags']
      all.each do |card|
        attributes = card.attributes.values_at(*['front','back'])
        tags = card.tags.collect { |tag| tag.name }
        tags = tags.join(';')
        attributes << tags
        csv << attributes
      end
    end
  end
end

app/views/pages/home.html.erb
<div class='page-down'>
  <div class='row'>
    <div class='home-side-bar-left large-3 columns'>
      <h4>Popular Tags</h4>
      <table>
        <tbody>
          <% @popular_tags.each do |tag| %>
            <tr>
              <td>
                <%= link_to tag.name, share_tag_path(tag.user, tag) %>
              </td>
              <td>
                <%= pluralize(tag.share_count, 'shares') %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <div class='review-lists large-6 columns'>
      <h4>Reviews in Progress</h4>
      <table>
        <tbody>
          <% current_user.review_lists.each do |review_list| %>
            <tr>
              <td>
                Tags:
                <% if review_list.tags.size > 0 %>
                  <%= review_list.tags_list %>
                <% else %>
                  None
                <% end %>
              </td>
              <td>
                Cards remaining: <%= review_list.cards.count %>
              </td>
              <td>
                <%= link_to 'Continue', review_list_path(review_list) %>
              </td>
            </tr>
          <% end %>
          <% if current_user.review_lists.count == 0 %>
            <td>None</td>
          <% end %>
        </tbody>
      </table>
    </div>

    <div class='home-side-bar-right large-3 columns'>
      <h4>Recent Tags</h4>
      <table>
        <tbody>
          <% @recent_tags.each do |tag| %>
            <tr>
              <td>
                <%= link_to tag.name, share_tag_path(tag.user, tag) %>
              </td>
              <td>
                <%= pluralize(tag.cards.count, 'card') %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

  <div class='row stats'>
    <h4>Statistics</h4>
    <div class='home-side-bar-left large-4 columns'>
      <h5>Quality of Recall</h5>
      <%= column_chart current_user.cards.where("quality_of_last_recall IS NOT NULL").group("quality_of_last_recall").count %>
    </div>

    <div class='review-lists large-4 columns'>
      <h5>Average Quality of Recall Per Tag</h5>
      <%= column_chart current_user.tags.inject({}) { |hash, tag| hash[tag.name] = tag.avg_quality;hash } %>
    </div>

    <div class='home-side-bar-right large-4 columns'>
      <h5>Reviews Due by Date</h5>
      <%= column_chart current_user.cards.where("next_repetition IS NOT NULL").group_by_day(:next_repetition).count %>
    </div>
  </div>
</div>

app/views/pages/review.html.erb
<div class="page-center page-down">

  <h3>Review</h3>

  <div class='form'>
    <dl class="tabs row" data-tab>
      <dd class="active"><a href="#all">All Cards</a></dd>
      <dd><a href="#tags">By Tags</a></dd>
      <dd><a href="#srs">SRS</a></dd>
    </dl>

    <div class="tabs-content row">
      <div class="content active small-12 columns" id="all">
        <div class='panel options-div'>
          <% review_list = @review_list.nil? ? ReviewList.new : @review_list %>
          <%= form_for(review_list) do |f| %>
            <% if review_list.errors.any? %>
              <div id="error_explanation">
                <ul>
                <% review_list.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
                <% end %>
                </ul>
              </div>
            <% end %>
            <div class="field panel">
              <%= f.label :amount %><br>
              <%= f.text_field :amount, placeholder: "Amount of cards to review" %>
            </div>
            <div class="field panel">
              <%= f.label :cards_due_after %><br>
              <%= f.text_field :due_after, placeholder: "Choose date", class: 'datepicker' %>
            </div>
            <div class="actions">
              <%= f.submit "Begin" %>
            </div>
          <% end %>
        </div>
      </div>

      <div class="content small-12 columns" id="tags">
        <div class='panel options-div'>
          <% review_list = @review_list.nil? ? ReviewList.new : @review_list %>
          <%= form_for(review_list) do |f| %>
            <% if review_list.errors.any? %>
              <div id="error_explanation">
                <ul>
                <% review_list.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
                <% end %>
                </ul>
              </div>
            <% end %>
            <div class="select panel">
              <%= f.label :tags %><br>
              <%= f.collection_select :tag_ids, current_user.tags, :id, :name, {}, { multiple: true } %>
            </div>
            <div class="field panel">
              <%= f.label :amount %><br>
              <%= f.text_field :amount, placeholder: "Amount of cards to review" %>
            </div>
            <div class="field panel">
              <%= f.label :cards_due_after %><br>
              <%= f.text_field :due_after, placeholder: "Choose date", class: 'datepicker' %>
            </div>
            <div class="actions">
              <%= f.submit "Begin" %>
            </div>
          <% end %>
        </div>
      </div>

       <div class="content small-12 columns" id="srs">
        <div class='panel options-div'>
          <% review_list = @review_list.nil? ? ReviewList.new : @review_list %>
          <%= form_for(review_list) do |f| %>
            <% if review_list.errors.any? %>
              <div id="error_explanation">
                <ul>
                <% review_list.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
                <% end %>
                </ul>
              </div>
            <% end %>
            <div class="field panel">
              <%= f.label :max_amount_of_cards %><br>
              <%= f.text_field :max, placeholder: "Max cards to review" %>
            </div>
            <div class="field panel">
              <%= f.label :amount_of_new_cards %><br>
              <%= f.text_field :new_count, placeholder: "New cards to review" %>
            </div>
            <div class="select panel">
              <%= f.label :tags %><br>
              <%= f.collection_select :tag_ids, current_user.tags, :id, :name, {}, { multiple: true } %>
            </div>
            <%= f.hidden_field :srs_review, :value => true%>
            <%= f.hidden_field :amount, :value => 1%>
            <div class="actions">
              <%= f.submit "Begin" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<%= content_for :extra_footer do %>
  <script>
    $(function(){
      $('.datepicker').pickadate()
    });
  </script>
<% end %>

app/views/pages/share.html.erb
<div class="page-center page-down">

  <div>
    <h3>Search Tags</h3>
    <%= search_form_for @q, url: search_pages_path,
                        html: { method: :post } do |f| %>
      <%= f.text_field :name_cont, placeholder: "Search by tag name" %>
      <%= f.submit %>
    <% end %>
  </div>

  <h3>Results</h3>
  <% @tags.each do |tag| %>
    <h3><%= link_to tag.name, share_tag_path(tag.user, tag) %></h3>
    <p>
      <div class='card-count'><%= pluralize(tag.cards.count, 'card') %></div>
      <div class='created-by'>created by: <%= link_to tag.user.username, user_path(tag.user) %></div>
      <br />shared <%= pluralize( tag.share_count, 'time' ) %>
    </p>
  <% end %>

  <%= paginate @tags %>
</div>

app/views/pages/sharetag.html.erb
<div class="page-center page-down">

  <h3><%= @tag.name %></h3>
  <p><%= link_to @tag.user.username, user_path(@tag.user) %>
  <%= button_to "Add to My Collection", copy_path(@tag) %></p>

  <% @cards.each do |card| %>
    <div class="panel">
      <%= simple_format(card.front) %>
      <hr>
      <%= simple_format(card.back) %>
    </div>
  <% end %>

  <%= paginate @cards %>
</div>

app/views/pages/welcome.html.erb
<div class='header-wrap'>
  <div class='header-text'>
    Flash
  </div>

  <div class='header-log-in'>
  <%= form_for(:user, :url => session_path(:user))  do |f| %>
    <div>
      <%= f.text_field :username, :autofocus => true, :placeholder => "Username/Email" %>
    </div>
    <div>
      <%= f.password_field :password, :placeholder => "Password" %>
    </div>


    <div><%= f.submit "Sign in" %></div>
  <% end %>
  </div>
</div>

<div class='welcome-content'>

  <div class="row">
    <div class="large-4 columns">
      <i class="fa fa-plus-square-o fa-3x"></i>
      <h4>Create</h4>
      <p>Make your own flash cards and tags to organize the information you want to study the way that fits you best</p>
    </div>
    <div class="large-4 columns">
      <i class="fa fa-files-o fa-3x"></i>
      <h4>Share</h4>
      <p>Find card sets other users have shared and add them to your collection, or share your own cards with others</p>
    </div>
    <div class="large-4 columns">
      <i class="fa fa-repeat fa-3x"></i>
      <h4>Review</h4>
      <p>Choose how you want to review your cards so you can ensure you get the most out of every study session</p>
    </div>
  </div>

</div>