config/routes.rb
Flash::Application.routes.draw do
  devise_for :users

  resources :cards, except: [:show] do
    collection do
      match 'search' => 'cards#index', via: [:get, :post], as: :search
    end
  end
  resources :card_imports, only: [:new,:create]
  resources :tags, except: [:show]
  resources :users, only: [:show]
  resources :review_lists, only: [:show, :new, :create]
  resources :pages do
    collection do
      match 'search' => 'pages#search', via: [:get, :post], as: :search
    end
  end

  get "/cards/:card_id", to: "cards#index", as: "cards_card"

  get "/tags/:tag_id", to: "tags#index", as: "tags_tag"

  post "/remove/:tag_id", to: "tags#remove", as: "tags_removetag"

  get "/review", to: "pages#review", as: "review"

  get "/share/(:page)", to: "pages#share", as: "share"

  get "/users/:id/:tag_id/(:page)", to: "pages#sharetag", as: "share_tag"

  post "/copy/:tag_id", to: "pages#copy", as: "copy"

  root 'pages#home'
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggings,
    inverse_of: :tag,
    dependent: :destroy
  has_many :cards,
    through: :taggings,
    inverse_of: :tags
  has_many :review_list_tags,
    dependent: :destroy
  has_many :review_lists,
    through: :review_list_tags,
    inverse_of: :tags
  belongs_to :user,
    inverse_of: :tags

  validates_presence_of :name
  validates_presence_of :user
  validates_presence_of :share_count

  paginates_per 10

  def avg_quality
    quality = 0
    count = 0
    self.cards.each do |card|
      if card.quality_of_last_recall
        quality += card.quality_of_last_recall
        count += 1
      end
    end
    return quality / count if count > 0
    0
  end

  def to_csv
    CSV.generate do |csv|
      csv << ['front','back','tags']
      self.cards.each do |card|
        attributes = card.attributes.values_at(*['front','back'])
        attributes << self.name
        csv << attributes
      end
    end
  end
end

app/controllers/tags_controller.rb
class TagsController < AuthenticatedController

  def index
    @tags = current_user.tags
    unless params[:tag_id].nil? || Tag.find(params[:tag_id]).user != current_user
      @tag = Tag.find(params[:tag_id]) unless params[:tag_id].nil?
    end
    respond_to do |format|
      format.html
      format.csv { render text: @tag.to_csv }
    end
  end

  def new
    @tag = Tag.new
  end

  def edit
    @tag = current_user.tags.find(params[:id])
  end

  def create
    @tag = current_user.tags.build(tag_params)
    if @tag.save
      redirect_to tags_path, notice: 'Tag was successfully created.'
    else
      @tags = current_user.tags - [@tag]
      render :index
    end
  end

  def update
    @tag = current_user.tags.find(params[:id])

    if @tag.update(tag_params)
      redirect_to tags_path, notice: 'Tag was successfully updated.'
    else
      @tags = current_user.tags
      render :index
    end
  end

  def destroy
    current_user.tags.find(params[:id]).destroy
    redirect_to tags_path, notice: 'Tag was successfully deleted.'
  end

  def remove
    @tag = Tag.find(params[:tag_id])
    @tag.taggings.each do |tagging|
      tagging.destroy
    end
    redirect_to tags_tag_path(@tag), notice: "Tag successfully removed from all cards."
  end

  private

  def tag_params
    params.require(:tag).permit(:name, :share)
  end

end

app/views/tags/_form.html.erb
<%= form_for(tag) do |f| %>
  <% if tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% tag.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field panel">
    <%= f.label :name %><br>
    <%= f.text_field :name, :maxlength=>"36" %>
    <%= f.label :share %>
    <%= f.check_box :share %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<% if !tag.id.nil? %>
  <div>
    <%= button_to "Delete", tag, :method => :delete %>
    <%= button_to "Remove from Cards", tags_removetag_path(tag) %>
  </div>
  <p><%= pluralize(tag.taggings_count,'card') %> under this tag.</p>
<% end %>

app/views/tags/index.html.erb
<div class='page-down'>
  <p><div class="row">
    <div class="large-2 columns side">

      <%= link_to "Import", new_card_import_path %> |
      <%= link_to_if(!@tag.nil?, "Export", "/tags/#{@tag.id if !@tag.nil?}.csv") %><br />
      <%= link_to "New Tag", '/tags' %>

      <ul class="side-nav side-nav-tags">
        <% @tags.each do |tag| %>
          <li>
            <span class='tag-delete'>
              <%= link_to "x", tag, :method => :delete, data: {confirm: "Delete?"} %>
            </span>
            <%= link_to truncate(tag.name, length: 19, omission: ''), tags_tag_path(tag.id),
              class: 'tag-link' %>
          </li>
        <% end %>
      </ul>

    </div>

    <div class="large-10 columns main">

      <div class='main'>
        <% tag = @tag.nil? ? Tag.new : @tag %>
        <%= render 'tags/form', tag: tag %>
      </div>

    </div>
  </div></p>
</div>