config/routes.rb
Flash::Application.routes.draw do
  devise_for :users

  resources :cards, except: [:show] do
    collection do
      match 'search' => 'cards#index', via: [:get, :post], as: :search
    end
  end
  resources :card_imports, only: [:new,:create]
  resources :tags, except: [:show]
  resources :users, only: [:show]
  resources :review_lists, only: [:show, :new, :create]
  resources :pages do
    collection do
      match 'search' => 'pages#search', via: [:get, :post], as: :search
    end
  end

  get "/cards/:card_id", to: "cards#index", as: "cards_card"

  get "/tags/:tag_id", to: "tags#index", as: "tags_tag"

  post "/remove/:tag_id", to: "tags#remove", as: "tags_removetag"

  get "/review", to: "pages#review", as: "review"

  get "/share/(:page)", to: "pages#share", as: "share"

  get "/users/:id/:tag_id/(:page)", to: "pages#sharetag", as: "share_tag"

  post "/copy/:tag_id", to: "pages#copy", as: "copy"

  root 'pages#home'
end

app/models/card.rb
class Card < ActiveRecord::Base
  include SuperMemo::SM2

  has_many :taggings,
    inverse_of: :card,
    dependent: :destroy
  has_many :tags,
    through: :taggings,
    inverse_of: :cards
  has_many :review_list_cards,
    dependent: :destroy
  has_many :review_lists,
    through: :review_list_cards,
    inverse_of: :cards
  belongs_to :user,
    inverse_of: :cards

  validates_presence_of :front
  validates_presence_of :back
  validates_presence_of :user

  paginates_per 20

  def self.to_csv
    CSV.generate do |csv|
      csv << ['front','back','tags']
      all.each do |card|
        attributes = card.attributes.values_at(*['front','back'])
        tags = card.tags.collect { |tag| tag.name }
        tags = tags.join(';')
        attributes << tags
        csv << attributes
      end
    end
  end
end

app/controllers/cards_controller.rb
class CardsController < AuthenticatedController

  def index
    @search = current_user.cards.search(params[:q])
    @cards = @search.result(distinct: true)
    unless params[:card_id].nil? || Card.find(params[:card_id]).user != current_user
      @card = Card.find(params[:card_id])
    end
    respond_to do |format|
      format.html
      format.csv { render text: @cards.to_csv }
    end
  end

  def new
    @card = Card.new
  end

  def edit
    @card = current_user.cards.find(params[:id])
  end

  def create
    @card = current_user.cards.build(card_params)
    if @card.save
      @card.tags = params[:card][:tag_ids].reject!{|x| x== ''}.map{|x| Tag.find(x.to_i)}
      @card.save!
      tag = eval(params[:card][:q])[:q]
      if tag
        filter = {}
        filter[:tags_id_eq] = tag["tags_id_eq"]
        redirect_to cards_path(q: filter), notice: 'Card was successfully created.'
      else
        redirect_to cards_path, notice: 'Card was successfully created.'
      end
    else
      @card.user = nil
      @search = current_user.cards.search(params[:q])
      @cards = @search.result(distinct: true)
      render :index
    end
  end

  def update
    @card = current_user.cards.find(params[:id])

    if @card.update(card_params)
      @card.tags = params[:card][:tag_ids].reject!{|x| x== ''}.map{|x| Tag.find(x.to_i)}
      tag = eval(params[:card][:q])[:q]
      if tag
        filter = {}
        filter[:tags_id_eq] = tag["tags_id_eq"]
        redirect_to cards_path(q: filter), notice: 'Card was successfully updated.'
      else
        redirect_to cards_path, notice: 'Card was successfully updated.'
      end
    else
      @search = current_user.cards.search(params[:q])
      @cards = @search.result(distinct: true)
      render :index
    end
  end

  def destroy
    current_user.cards.find(params[:id]).destroy
    redirect_to cards_path(q: params[:q]), notice: 'Card was successfully deleted.'
  end

  private

  def card_params
    params.require(:card).permit(:front, :back)
  end

end

app/views/cards/_form.html.erb
<%= form_for(card) do |f| %>
  <% if card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
      <% card.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field panel">
    <%= f.label :front %><br>
    <%= f.text_area :front %>
  </div>
  <div class="field panel">
    <%= f.label :back %><br>
    <%= f.text_area :back %>
  </div>
  <div class="select panel">
    <%= f.label :tags %><br>
    <%= f.collection_select :tag_ids, current_user.tags, :id, :name, {}, { multiple: true } %>
  </div>
  <%= f.hidden_field :q, {:value => {:q => params[:q]}} %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<% if !card.front.nil? && card.front != '' && card.back != '' %>
  <%= button_to "Delete", card_path(card,q: params[:q]), :method => :delete %>
<% end %>

app/views/cards/index.html.erb
<div class='page-down'>
  <p><div class="row">
    <div class="large-2 columns side">

      <%= link_to "Import", new_card_import_path %> |
      <%= link_to "Export", '/cards.csv' %><br />
      <%= link_to "New Card", cards_path(q: params[:q]) %>
      <%= search_form_for @search, url: search_cards_path,
                        html: { method: :post } do |f| %>
        <%= f.select :tags_id_eq, current_user.tags.collect{|c| [c.name, c.id]},{include_blank: "All"} %>
        <%= f.submit "Filter", class: 'hidden filter'%>
      <% end %>

      <ul class="side-nav side-nav-tags">
        <% @cards.each do |card| %>
          <li>
            <span class='tag-delete'>
              <%= link_to "x", card_path(card,q: params[:q]), :method => :delete, data: {confirm: "Delete?"} %>
            </span>
            <%= link_to truncate(card.front, length: 19, omission: ''),
                        cards_card_path(card.id, q: params[:q]),
              class: 'card-link' %>
          </li>
        <% end %>
      </ul>

    </div>

    <div class="large-10 columns main">

      <div class='main'>
        <% card = @card.nil? ? Card.new : @card %>
        <%= render 'cards/form', card: card %>
      </div>

    </div>
  </div></p>
</div>